nome = input('Digite o seu nome: ')
dia_nascimento = input('Digite o dia do seu nascimento: ')
mes_nascimento = input ('Digite o mês do seu nascimento: ')
ano_nascimento = input ('Digite o ano do seu nascimento: ')
print('Olá', nome, 'Você nasceu em', dia_nascimento, 'de', mes_nascimento, 'de', ano_nascimento)
